# Generated by Django 5.1.5 on 2025-01-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField(blank=True, null=True, verbose_name='Comment Parent')),
                ('text', models.TextField(blank=True, max_length=255, null=True, verbose_name='Item Text')),
                ('date_posted', models.DateTimeField(null=True, verbose_name='Creation Time')),
                ('kids', models.JSONField(blank=True, null=True, verbose_name='Kids')),
                ('type', models.CharField(max_length=255, verbose_name='Item Type')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Author')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField(null=True)),
                ('type', models.CharField(max_length=255, verbose_name='Item Type')),
                ('author', models.CharField(max_length=255, verbose_name='Item Author')),
                ('date_created', models.DateTimeField(null=True, verbose_name='Creation Time')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Is Item Posted?')),
                ('kids', models.JSONField(blank=True, null=True, verbose_name='Kids')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Item Text')),
                ('descendants', models.IntegerField(blank=True, null=True, verbose_name='Comment count')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Item Score')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Item url')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Item Title')),
            ],
        ),
    ]
